server:
  port: 8401

spring:
  profiles:
    active: @env@
  application:
    name: USER_CENTER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.kangyonggan.uc.model

mapper:
  mappers: com.kangyonggan.uc.plugin.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
